# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='persona',
            fields=[
                ('Nombre', models.CharField(max_length=30)),
                ('Apellido1', models.CharField(max_length=30)),
                ('Apellido2', models.CharField(max_length=30)),
                ('ID', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('Correo', models.EmailField(max_length=254)),
            ],
        ),
    ]
