# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='alarma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_maxima', models.DateTimeField()),
                ('fecha_aviso', models.DateTimeField()),
                ('realizado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='correspondencia',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_recibido', models.DateField()),
                ('oficio', models.CharField(max_length=40)),
                ('fecha_oficio', models.DateField()),
                ('destinatario', models.CharField(max_length=40)),
                ('copia', models.TextField()),
                ('remitente', models.CharField(max_length=40)),
                ('asunto', models.TextField()),
                ('estado', models.CharField(max_length=100)),
                ('observacion', models.TextField()),
                ('adjunto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='enlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hijo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hijo', to='scc.correspondencia')),
                ('padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='padre', to='scc.correspondencia')),
            ],
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='Apellido1',
            new_name='apellido1',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='Apellido2',
            new_name='apellido2',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='Correo',
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='recibido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scc.persona'),
        ),
        migrations.AddField(
            model_name='alarma',
            name='correspondencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scc.correspondencia'),
        ),
    ]
