# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 02:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scc', '0002_auto_20171129_0202'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alarma',
            table='alarma',
        ),
        migrations.AlterModelTable(
            name='correspondencia',
            table='correspondencia',
        ),
        migrations.AlterModelTable(
            name='enlace',
            table='enlace',
        ),
        migrations.AlterModelTable(
            name='persona',
            table='persona',
        ),
    ]
